schema: "classroom50/repo-config/v1"
classroom: "developing-the-interactive-web"
assignment: "project-1"
secret: "coos6z1d"
owner:
  username: "zberrier"
  id: 145724606
  accepted_at: "2026-09-22T13:21:33Z"
source:
  owner: "CSCI-5117-F26"
  owner_id: 324118398
  repo: "Project-1"
  branch: "main"
